version: '3.8'

services:
  mcp_server:
    build: .
    command: python mcp_server/server.py
    ports:
      - "8001:8001"
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    networks:
      - app-network
    restart: always
    # volumes:
    #   - ./mcp_server:/app/mcp_server

  langgraph_app:
    build: .
    command: langgraph dev --allow-blocking
    working_dir: /app
    ports:
      - "2024:2024"
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./app:/app
    networks:
      - app-network
    depends_on:
      - mcp_server
    restart: always

networks:
  app-network:
    driver: bridge